Connection module for the Anthropic Claude API.
Responsibility: send prompts and return the generated text.
 
Usage:
    from ai.claude_client import ask_claude
    response = ask_claude("What is the impact of AMR?")
"""
 
import os
import anthropic
 
 
def ask_claude(prompt: str) -> str:
    """
    Sends a prompt to Claude and returns only the generated text.
 
    Args:
        prompt (str): The prompt text to send to Claude.
 
    Returns:
        str: The text generated by Claude.
 
    Raises:
        EnvironmentError: If the ANTHROPIC_API_KEY environment variable is not set.
        anthropic.APIConnectionError: If there are connectivity issues with the API.
        anthropic.APIStatusError: If the API returns an HTTP error.
    """
 
    # ── 1. Read the API Key from environment variables ────────────────────
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "The ANTHROPIC_API_KEY environment variable is not set. "
            "Please add it to your environment or Streamlit Cloud Secrets."
        )
 
    # ── 2. Create the Anthropic client ────────────────────────────────────
    client = anthropic.Anthropic(api_key=api_key)
 
    # ── 3. Send the prompt and retrieve the response ──────────────────────
    try:
        message = client.messages.create(
            model="claude-sonnet-4-6",   # Recommended model: speed/quality balance
            max_tokens=2048,              # Sufficient for detailed recommendations
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )
 
        # Extract only the text from the first content block
        return message.content[0].text
 
    except anthropic.APIConnectionError as e:
        # Network or connectivity error
        raise anthropic.APIConnectionError(
            f"Could not connect to the Anthropic API: {e}"
        ) from e
 
    except anthropic.APIStatusError as e:
        # HTTP error returned by the API (401, 429, 500, etc.)
        raise anthropic.APIStatusError(
            message=f"Anthropic API error (HTTP {e.status_code}): {e.message}",
            response=e.response,
            body=e.body
        ) from e
