AI-powered recommendation engine for the ResistAI project.
Builds contextual prompts from simulation parameters
and sends them to Claude to obtain clear policy recommendations.
 
Usage:
    from ai.recommendation_engine import generate_recommendation
    text = generate_recommendation(country="Peru", delay_years=5, ...)
"""
 
from ai.claude_client import ask_claude
 
 
def generate_recommendation(
    country: str,
    delay_years: int,
    funding_level: str,
    stewardship_rate: float,
    rd_investment: str,
    deaths: int,
    healthcare_cost: float,
    gdp_loss: float
) -> str:
    """
    Generates public policy recommendations using Claude based on
    antimicrobial resistance simulation parameters.
 
    Args:
        country          (str):   Country being analyzed (e.g. "Peru", "Brazil").
        delay_years      (int):   Years of delay in implementing AMR policies.
        funding_level    (str):   Funding level ("Low", "Medium", "High").
        stewardship_rate (float): Stewardship program adoption rate (0-100%).
        rd_investment    (str):   R&D investment level ("Low", "Medium", "High").
        deaths           (int):   Projected additional deaths due to the delay.
        healthcare_cost  (float): Healthcare cost increase (USD millions).
        gdp_loss         (float): Projected GDP loss (USD millions).
 
    Returns:
        str: Policy recommendation text generated by Claude, structured in
             clear sections and accessible language for decision-makers.
    """
 
    # ── 1. Format numeric values for the prompt ───────────────────────────
    deaths_formatted    = f"{deaths:,}"
    healthcare_cost_fmt = f"${healthcare_cost:,.1f}M"
    gdp_loss_fmt        = f"${gdp_loss:,.1f}M"
    stewardship_pct     = f"{stewardship_rate:.0f}%"
 
    # ── 2. Build the structured prompt ────────────────────────────────────
    prompt = f"""
You are a public health policy advisor specializing in antimicrobial resistance (AMR).
Your audience is a government policymaker with no technical background.
Use clear, simple, and empathetic language. Avoid jargon.
 
## SIMULATION CONTEXT
 
- **Country:** {country}
- **Policy Delay:** {delay_years} year(s) without implementing AMR policies
- **Funding Level:** {funding_level}
- **Stewardship Adoption Rate:** {stewardship_pct}
- **R&D Investment Level:** {rd_investment}
 
## PROJECTED IMPACT OF THIS DELAY
 
- **Additional Deaths:** {deaths_formatted} people
- **Healthcare Cost Increase:** {healthcare_cost_fmt} USD
- **GDP Loss:** {gdp_loss_fmt} USD
 
---
 
Based on this simulation, please provide a structured policy brief with the following sections.
Use plain language as if explaining to someone making urgent national decisions.
 
### 1. SITUATION SUMMARY
Write 2-3 sentences explaining what this delay means in simple terms for {country}.
 
### 2. HUMAN IMPACT
Explain in human terms what {deaths_formatted} additional deaths means.
Use relatable comparisons (e.g., equivalent to filling X stadiums, X families affected).
 
### 3. ECONOMIC IMPACT
Explain what a loss of {gdp_loss_fmt} USD means for {country}'s economy in practical terms.
Mention what could have been funded instead (hospitals, schools, salaries).
 
### 4. IMMEDIATE ACTIONS (Next 30 days)
List 3 specific actions the government can take RIGHT NOW.
Each action should include an estimated number of lives that could be saved.
 
### 5. SHORT-TERM ACTIONS (3-12 months)
List 3 policy measures to implement within the year.
Each should include estimated lives saved and brief implementation notes.
 
### 6. LONG-TERM ACTIONS (1-5 years)
List 3 structural investments or reforms.
Each should include projected lives saved and economic benefit.
 
### 7. FINAL MESSAGE TO THE POLICYMAKER
End with a 2-3 sentence direct, compelling message that conveys the urgency
without being alarmist. Make it clear that action today saves lives tomorrow.
 
---
Format the response clearly with the section headers shown above.
Keep each section concise but impactful. Do NOT use overly technical terminology.
"""
 
    # ── 3. Call Claude and return the response ────────────────────────────
    return ask_claude(prompt)
